### ISSUE TITLE
Please provide better description

### ISSUE THREAD

**Issue by GermanBluefox** [instalator/ioBroker.lgtv-rs#1]
Please extend the description: https://github.com/instalator/ioBroker.lgtv-rs/blob/master/io-package.json#L22

This is the new rule, additionally to tests and readme and npm, it is now required to provide good explanation about adapter. 
Please write something like: Controls LG TV over RS232 interface.

**Comment by instalator** [comment]
ОК?

**Comment by GermanBluefox** [comment]
Yes
