### ISSUE TITLE
Update stable version in repo from 0.0.4 to 0.1.0

### ISSUE THREAD

**Issue by GermanBluefox** [instalator/ioBroker.lgtv-rs#12]
# Think about update stable version to 0.1.0
**Version**: stable=**0.0.4** (867 days old) => latest=**0.1.0** (15 days old)
**Installs**: stable=**80** (87.91%), latest=**10** (10.99%), total=**91**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L673)

**Comment by instalator** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/778
