### ISSUE TITLE
Problems with the usage of the adapter / connection to LG TV

### ISSUE THREAD

**Issue by eric1905** [instalator/ioBroker.lgtv-rs#4]
Hi Instalator,

I have a question regarding the connection to my LG via RS232.
As you wrote in your adapter page, I have:
1 Arduino Uno
1 W5100 shield
1 RS232 module

First question:
Is the RS232 connected via 3.3 V or 5V?

2. If I use the Script from the page you linked: https://github.com/stepansnigirev/ArduinoSerialToEthernet#etherneth-or-ethernet2h
I am not able to upload it to my arduino, because Arduino UNO does not support Serial1

3. If I try to upload the Script from your page for ioBroker:
https://translate.google.de/translate?hl=de&sl=ru&u=https://blog.instalator.ru/archives/339&prev=search

I receive the message:
serial_to_ethernet:10: error: 'callback' was not declared in this scope

I think this is because somehting has changed and i have to provide the method before the usage of callback, so i inserted:
// Callback function header
void callback(char* topic, byte* payload, unsigned int length);
 before line 10.

Then i have an error because of too much variables. So i removed some commands for the tv input mode, just for testing purposes, and i was able to upload the sketch.
But then i am not able to connect via ioBroker.

Is there still something I have forgotten which must be changed?
What about this:
11
#define id_connect "myhome-RS232"
12
#define Prefix_subscribe "myhome/RS232/"

Do i have to configure it?

Is port 23 in ioBroker adapter ok? Where is it defined?

I expect the wires are as follows:
RS232 --> Arduino UNO
TX --> RX
RX --> TX
GND --> GND
VCC --> 3.3/5/12?

Best regards,
Eric

**Comment by instalator** [comment]
Код естественно нужно изменить для себя. Вот возьми готовый: 
https://github.com/instalator/TelnetToEthernet/blob/master/main.ino
